### ISSUE TITLE
Index was out of range BitConverter.ToInt32

### ISSUE THREAD

**Issue by eternal-lc** [aiusepsi/SourceRcon#1]

**Comment by aiusepsi** [comment]
What's BCBD2? Is it a Source game?

On 25 June 2011 12:56, eternal-lc <
reply@reply.github.com>wrote:

> I obtain this error when I try to connect to a BCBD2 server.
> I am under gentoo 64 bits.
> 
> Enter IP Address:
> 'host'
> Enter port:
> 'port'
> Enter password:
> 'passwd'
> Receive Callback. Packet: 0 First packet: True, Bytes so far: 0
> Receive Callback. Packet: 0 First packet: False, Bytes so far: 0
> Complete packet.
> 
> Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of
> range. Must be non-negative and less than the size of the collection.
> Parameter name: startIndex
>  at System.BitConverter.PutBytes (System.Byte\* dst, System.Byte[] src,
> Int32 start_index, Int32 count) [0x00000] in <filename unknown>:0
>  at System.BitConverter.ToInt32 (System.Byte[] value, Int32 startIndex)
> [0x00000] in <filename unknown>:0
>  at SourceRcon.RCONPacket.ParseFromBytes (System.Byte[] bytes,
> SourceRcon.SourceRcon parent) [0x00000] in <filename unknown>:0
>  at SourceRcon.SourceRcon.ProcessIncomingData (SourceRcon.RecState state)
> [0x00000] in <filename unknown>:0
>  at SourceRcon.SourceRcon.ReceiveCallback (IAsyncResult ar) [0x00000] in
> <filename unknown>:0
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aiusepsi/SourceRcon/issues/1

## 

Andy
